const stickers = {
  "gratitude": {
    "oni-chan": {
      id: 65091,
      pack: "oni-chan",
      pack_id: 1361,
      type: "gratitude",
      text: "АРИГАТО!",
      textLanguage: "ru",
    },
    "Asteria": {
      id: 86140,
      previewImageUrl: "https://vk.com/sticker/1-86140-512",
      previewImageWithBackground: "https://vk.com/sticker/1-86140-512b",
      pack: "Asteria",
      pack_id: 1835,
      type: "gratitude",
      text: "БЛАГОДАРЮ",
      textLanguage: "ru",
    },
    "Best friends": {
      id: 88368,
      previewImageUrl: "https://vk.com/sticker/1-88368-512",
      previewImageWithBackground: "https://vk.com/sticker/1-88368-512b",
      pack: "Best friends",
      type: "gratitude",
      text: "СПАСИБО",
      textLanguage: "ru",
    },
    "Your vmoji": {
      id: 73618,
      previewImageUrl: "https://sun1-55.userapi.com/7i4oPsrE0EUil-6mwFDnHyvjq9z_ASLtOu4ROA/LdoH_FZZWBQ.png",
      previewImageWithBackground: "https://sun1-95.userapi.com/ddXDpxdYvLlAp2lHVAK66QAsHyQHI3PROEDcmg/EXMuJwJGJ5Y.png",
      pack: "Your vmoji",
      type: "gratitude",
      text: "МЕРСИ",
      textLanguage: "ru",
    },
    "No Words Needed": {
      id: 94365,
      previewImageUrl: "https://vk.com/sticker/1-94365-512",
      previewImageWithBackground: "https://vk.com/sticker/1-94365-512b",
      pack: "No Words Needed",
      type: "gratitude",
      text: "СПАСИБО",
      textLanguage: "ru",
    },
    "Vladik": {
      id: 86539,
      previewImageUrl: "https://vk.com/sticker/1-86539-512",
      previewImageWithBackground: "https://vk.com/sticker/1-86539-512b",
      pack: "Vladik",
      type: "gratitude",
      text: "СПАСИБО!",
      textLanguage: "ru",
    },
    "Bengal and Somali": {
      id: 91892,
      previewImageUrl: "https://vk.com/sticker/1-91892-512",
      previewImageWithBackground: "https://vk.com/sticker/1-91892-512b",
      pack: "Bengal and Somali",
      type: "gratitude",
      text: "СПАСИБО!",
      textLanguage: "ru",
    },
    "Emily": {
      id: 72149,
      previewImageUrl: "https://vk.com/sticker/1-72149-512",
      previewImageWithBackground: "https://vk.com/sticker/1-72149-512b",
      pack: "Emily",
      type: "gratitude",
      text: "СПАСИБО, ЗАЮШ",
      textLanguage: "ru",
    },
  },
  "greeting": {
    "Elinor": {
      id: 85081,
      previewImageUrl: "https://vk.com/sticker/1-85081-512",
      previewImageWithBackground: "https://vk.com/sticker/1-85081-512b",
      pack: "Elinor",
      type: "greeting",
      text: "ХАЙ, БИЧ",
      textLanguage: "ru",
    },
    "Emily": {
      id: 72168,
      previewImageUrl: "https://vk.com/sticker/1-72168-512",
      previewImageWithBackground: "https://vk.com/sticker/1-72168-512b",
      pack: "Emily",
      type: "greeting",
      text: "ПРИВЕТ, ЗАЙ",
      textLanguage: "ru",
    },
    "Heartfelt stickers": {
      id: 92708,
      previewImageUrl: "https://vk.com/sticker/1-92708-512",
      previewImageWithBackground: "https://vk.com/sticker/1-92708-512b",
      pack: "Heartfelt stickers",
      type: "greeting",
      text: "ПРИВЕТ",
      textLanguage: "ru",
    },
    "Tong": {
      id: 84592,
      previewImageUrl: "https://vk.com/sticker/1-84592-512",
      previewImageWithBackground: "https://vk.com/sticker/1-84592-512b",
      pack: "Tong",
      type: "greeting",
      text: "ПРИВЕТ, ДРУГ",
      textLanguage: "ru",
    },
    "Your vmoji": {
      id: 73601,
      previewImageUrl: "https://sun1-56.userapi.com/xnz4QcDDU41fsduvDvEUCPevVMxRMZgFsOPHHg/DmWhPkn1jKw.png",
      previewImageWithBackground: "https://sun1-16.userapi.com/XiZCxo2MHQCFTNXaI5cectj6WXkdN38eRAP2kw/FgfQ7bY9Vzk.png",
      pack: "Your vmoji",
      type: "greeting",
    },
    "Winter vmoji": {
      id: 81987,
      previewImageUrl: "https://sun1-57.userapi.com/oU3AHHeZkex95AL_36v5bGRIRZOe3JqPNFaC_g/WcHwRXqOLD0.png",
      previewImageWithBackground: "https://sun1-97.userapi.com/RYZABEdEnKlCZi2Bpw6i81E_q2m9GJ5Mnq3UWw/Qu80YNCn2l4.png",
      pack: "Winter vmoji",
      type: "greeting",
    }
  }
};

module.exports = {
  stickers
};